### ISSUE TITLE
is this app compatible with pihole v5.0?

### ISSUE THREAD

**Issue by xxcriticxx** [joshspicer/pihole-mobile-app#10]
fyi version 5.0 just dropped to master

**Comment by joshspicer** [comment]
Just pushed a fix for v5.  If you're using the App Store build, the fix will be live in version 1.2 (once Apple approves it).

**Comment by xxcriticxx** [comment]
@joshspicer let me know once the new version is live in the app store

thanks for this great app!

**Comment by joshspicer** [comment]
happy you’re enjoying it. Should be live :)

**Comment by xxcriticxx** [comment]
thanks a million
