### ISSUE TITLE
Feature Request: PIN Lock Set Credentials

### ISSUE THREAD

**Issue by BPWZHJCZ** [joshspicer/pihole-mobile-app#11]
It would be good if it was possible to lock, maybe with a PIN, the settings. 

The use case is that I would share the app with other people in the household in case they need to temporarily disable the PiHole and if they click Set Credentials, it seems to reset/not save state.

A PIN Lock would mean only authorized users could Set/Change Credentials.

If not the above, just some way of saving state to avoid people resetting credentials.

**Comment by joshspicer** [comment]
Hello! Thanks for the feedback.  Do note that if you were to end up in that screen, pressing "cancel" would not clear what was previously there.

That said, I'll autofill back in the credentials so that people don't accidentally clear creds anymore.

**Comment by BPWZHJCZ** [comment]
Thanks. Just saw the cancel button. My bad.
