### ISSUE TITLE
Design idea

### ISSUE THREAD

**Issue by F3000** [joshspicer/pihole-mobile-app#14]
I have seen this in a Covid-19 app and thought this layout would fit into your app :) 

![image](https://user-images.githubusercontent.com/8161283/81741762-52ea0200-949f-11ea-8159-d6ae85a47646.jpeg)

**Comment by joshspicer** [comment]
Thanks! I'll take all the help I can get with design :)

**Comment by F3000** [comment]
I think the app from my picture was written in Swift-Ui . 

Can you combine this with your language ?
