### ISSUE TITLE
Feature request : save old values

### ISSUE THREAD

**Issue by F3000** [joshspicer/pihole-mobile-app#15]
at the moment when the user opens the app all fields are blank .

Would be good when the app display the last values when a user open it

**Comment by joshspicer** [comment]
Added!  In next version (1.3), app will auto-refresh data when opened.

**Comment by F3000** [comment]
Thanks . Is background sync also possible ?

**Comment by joshspicer** [comment]
You want it to update when you're not looking at it??

**Comment by F3000** [comment]
Like in other apps . Not every 10 min but every 5 hours etc...
