### ISSUE TITLE
Server not found 

### ISSUE THREAD

**Issue by CelticWebSolutions** [joshspicer/pihole-mobile-app#2]
I believe this could work but not sure if it's implemented. So hoping if its' not, its something you can implement easily.

I use PiHole behind a reverse proxy so that I can access it externally, it just make sit easier if my family need it disabled, I can log in and disable it.

I use a domain name to access it e.g. https://pihole.mydomain.com the domain then routes through to my NAS which uses reverse proxy  to direct it on to the pi that's running PiHole.  All works fine.  For access via web from any browser, internally or externally to my home.

If I add the domain name in your app, it can't find my server. It finds it with the local IP without a problem, Is there a way around this to make it work with the domain name please? 

Thanks in advance!
Huw

**Comment by joshspicer** [comment]
This is the line that parses the URL you enter.  `dest` below is the exact input that you type in.  If you just type in `pihole.mydomain.com` without the `http://`, does it work?

https://github.com/joshspicer/pihole-mobile-app/blob/7b9922cf2941c9b401bf833e92b8ce7fc41d4d20/PiholeDashboard/Views/SettingsPage.xaml.cs#L39

Will definitely improve this parsing in the future (admittedly a lazy way to do it).

**Comment by joshspicer** [comment]
If above doesn't work, #3 should fix your issue.  I'll be pushing it to the App Store shortly, or you're welcome to build it yourself.  Let me know if it helps!

**Comment by CelticWebSolutions** [comment]
Hi,

Thanks for the response, I think #3 will be the winner, my url is https so even when I enter port 443, it's still preceded with http by the looks of your code. If I get a chance in the morning, I'll build the app, sign it and load it on to my phone.  Think I can do it, I've only ever really built Android apps.  Can't be that difficult, can it? LOL

**Comment by joshspicer** [comment]
Just FYI - Apple was surprisingly quick and my fix is live on the App Store!  Feel free to try that instead if it's easier for you :)

**Comment by CelticWebSolutions** [comment]
That’s quick for Apple! 

You’ll also be glad to know that it has indeed fixed the issue.  I can now connect to and refresh data from my Pihole server remotely.

Thanks for the quick fix! Keep up the great work!
