### ISSUE TITLE
Editing primary API key overwrites backup API key and vice versa

### ISSUE THREAD

**Issue by TreatyOfRome** [joshspicer/pihole-mobile-app#26]
Bug: Editing primary API key overwrites backup API key and vice versa

Hard- / software:
I'm using PiContrHOLE v.1.4 on iOS 12.4.8 on an iPhone 6 with 2 Pi-holes v. 5.1.2 on separate SingleBoardComputers.

Steps to reproduce:
Trying to add my backup instance to the app. I add my primary URI, then scan my QR-API key and save. I use the radio button to select my backup settings. I enter my backup URI, scan my QR-API key and save. 

Expected behavior is that both (different) API keys are stored and used. 
Experienced behavior is that only the last scanned QR-API key is saved and used for both my primary and backup instance. I'm only able to change the settings on one of my instances (the one of which I saved the API key the latest).

**Comment by joshspicer** [comment]
huh interesting, ill try tonight.  

My two pi-holes have the same password, and subsequently the same api key, so i bet thats why i missed it.

**Comment by joshspicer** [comment]
I had the conditions flipped. Thanks for pointing it out
