### ISSUE TITLE
Settings page doesn't show scan button or help info button

### ISSUE THREAD

**Issue by TreatyOfRome** [joshspicer/pihole-mobile-app#27]
Bug: Settings page doesn't show scan button or help info button

Hard- / software:
I'm using PiContrHOLE v.1.4 on iOS 12.4.8 on an iPhone 6.

Steps to reproduce:
When I enter the settings page in your app (top right button) I don't see any button to activate the QR-scanner. But when I tap the red area, the QR scanner is activated. 

I don't see any help info button, but when I roughly tap the blue area, the help info is presented. I expect to see visible buttons.
 
![PiContrHOLE](https://user-images.githubusercontent.com/26620973/91754097-61783880-ebb8-11ea-8fbc-512056b3f0c0.jpg)

**Comment by TreatyOfRome** [comment]
Not sure if this is related, but I can't see any button to activate dark mode.

**Comment by joshspicer** [comment]
yikes! Thanks for pointing that out.

Dark mode is triggered based on your OS settings. So if your iphone is in dark mode system-wide, the app will be as well! (and you should be able to see the buttons in dark mode)
