### ISSUE TITLE
Radio Buttons Alignment Issue

### ISSUE THREAD

**Issue by mohan7690** [joshspicer/pihole-mobile-app#32]
Alignment of Radio Buttons Text has moved down and on the toggles page the radio buttons are overlapping with time of the device.

Hardware : iPhone 7
Software : IOS 13.7 (Latest)
PiHole Verstion : 5.1.2
![InkedPNG image 2_LI](https://user-images.githubusercontent.com/44416339/92176031-8657f000-edf2-11ea-9239-cb69c2fb4d09.jpg)
![InkedPNG image 3_LI](https://user-images.githubusercontent.com/44416339/92176036-8821b380-edf2-11ea-88c2-50baff18f60e.jpg)
![InkedPNG image_LI](https://user-images.githubusercontent.com/44416339/92176038-8952e080-edf2-11ea-8cf7-31fe19e03169.jpg)

**Comment by mohan7690** [comment]
> Thanks for taking the time to submit this bug!
> 
> If you force quit the app, do they still stay misaligned? I've seen this before temporarily, but not sure how it gets into that state.

After Force close and restarting the mobile it was back to normal.

**Comment by joshspicer** [comment]
Glad that fixed it, although regardless we shouldn't have to quit the app to fix the formatting ( not too sure why it does this)
