### ISSUE TITLE
Unable to run App on Android

### ISSUE THREAD

**Issue by mohan7690** [joshspicer/pihole-mobile-app#33]
Unable to run the application on Android, tried to run without any changes to the code and it is failing at the runtime, build is success without any errors but not running looks like runtime error preventing the app to run.

Platform Details:
 Client : Windows 10
 Android Emulator : Pixel 2 API 29

[Error Text.txt](https://github.com/joshspicer/pihole-mobile-app/files/5172404/Error.Text.txt)

![Error](https://user-images.githubusercontent.com/44416339/92194370-5d018900-ee1f-11ea-87d7-a11cb5e940e6.png)

**Comment by joshspicer** [comment]
you'll need to follow the instruction in that exception and "opt-in" to AppTheme-experimental 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/experimental-flags#enable-flags-in-platform-projects

If you do get around to please submit a PR! Eventually i'll get around to giving the Android version some attention :)

**Comment by joshspicer** [comment]
You can see in the iOS/AppDelegate file which experimental flags I am setting on that side. Android should mirror

**Comment by mohan7690** [comment]
Have reflected required flags and its working now and created PR

**Comment by joshspicer** [comment]
#34
