### ISSUE TITLE
Bug: disable of system didn’t work

### ISSUE THREAD

**Issue by F3000** [joshspicer/pihole-mobile-app#6]
When I press the button to disable it doesent  have effects

**Comment by joshspicer** [comment]
Did you enter the WEBPASSWORD key found in `pihole/setupVars.conf` for your API key?  Note that this **isn't** the API key you get from the Web UI.  

Are you able to to connect to the server and refresh the stats on "Browse" page?  

Does any alert message pop up when you press the button?  What does that text say?

**Comment by joshspicer** [comment]
Also note that in the latest update (app store v1.1) you may need to simply re-add your pi-hole's URI.  Make sure you add it with the HTTP/HTTPS protocol in the front.

**Comment by F3000** [comment]
> Did you enter the WEBPASSWORD key found in `pihole/setupVars.conf` for your API key?  Note that this **isn't** the API key you get from the Web UI.  
> 
> 
> 
> Are you able to to connect to the server and refresh the stats on "Browse" page?  
> 
> 
> 
> Does any alert message pop up when you press the button?  What does that text say?

I can connect fine . Refresh is also possible.  I have only “read access” .

**Comment by joshspicer** [comment]
Please answer all the questions I ask so I can better understand if this is something to do with my app. What does the pop-up alert say when you press a button? Are you using the WEBPASSWORD?

I'm not sure what "read access" only means in this context.  I suspect that is probably your issue.

**Comment by F3000** [comment]
I have used the web password .  I see no action when pressing things. 

But i think you can close this issue. I also cant click things on the webui. 
E.x.: i press enable but the website activate it until reload . After that it is disabled again (but i have checked via SSh the server is running) .


I think i will update to V5 in the next days and check it again
